//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 01:48:05 PM EET 
//


package com.dnb.services.industry;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IndustryChapterNameEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IndustryChapterNameEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="IndustryOverview"/>
 *     &lt;enumeration value="QuarterlyIndustryUpdate"/>
 *     &lt;enumeration value="BusinessChallenges"/>
 *     &lt;enumeration value="TrendsAndOpportunities"/>
 *     &lt;enumeration value="ExecutiveInsight"/>
 *     &lt;enumeration value="CallPreparationQuestions"/>
 *     &lt;enumeration value="FinancialInformation"/>
 *     &lt;enumeration value="IndustryForecast"/>
 *     &lt;enumeration value="IndustryWebsites"/>
 *     &lt;enumeration value="GlossaryOfAcronyms"/>
 *     &lt;enumeration value="IndustryIndicators"/>
 *     &lt;enumeration value="FastFacts"/>
 *     &lt;enumeration value="All"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IndustryChapterNameEnum")
@XmlEnum
public enum IndustryChapterNameEnum {

    @XmlEnumValue("IndustryOverview")
    INDUSTRY_OVERVIEW("IndustryOverview"),
    @XmlEnumValue("QuarterlyIndustryUpdate")
    QUARTERLY_INDUSTRY_UPDATE("QuarterlyIndustryUpdate"),
    @XmlEnumValue("BusinessChallenges")
    BUSINESS_CHALLENGES("BusinessChallenges"),
    @XmlEnumValue("TrendsAndOpportunities")
    TRENDS_AND_OPPORTUNITIES("TrendsAndOpportunities"),
    @XmlEnumValue("ExecutiveInsight")
    EXECUTIVE_INSIGHT("ExecutiveInsight"),
    @XmlEnumValue("CallPreparationQuestions")
    CALL_PREPARATION_QUESTIONS("CallPreparationQuestions"),
    @XmlEnumValue("FinancialInformation")
    FINANCIAL_INFORMATION("FinancialInformation"),
    @XmlEnumValue("IndustryForecast")
    INDUSTRY_FORECAST("IndustryForecast"),
    @XmlEnumValue("IndustryWebsites")
    INDUSTRY_WEBSITES("IndustryWebsites"),
    @XmlEnumValue("GlossaryOfAcronyms")
    GLOSSARY_OF_ACRONYMS("GlossaryOfAcronyms"),
    @XmlEnumValue("IndustryIndicators")
    INDUSTRY_INDICATORS("IndustryIndicators"),
    @XmlEnumValue("FastFacts")
    FAST_FACTS("FastFacts"),
    @XmlEnumValue("All")
    ALL("All");
    private final String value;

    IndustryChapterNameEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IndustryChapterNameEnum fromValue(String v) {
        for (IndustryChapterNameEnum c: IndustryChapterNameEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
