//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 01:48:05 PM EET 
//


package com.dnb.services.industry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for InquiryDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InquiryDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IndustryCode" type="{http://services.dnb.com/IndustryProductServiceV2.0}InquiryIndustryCodeType" minOccurs="0"/>
 *         &lt;element name="Location" type="{http://services.dnb.com/IndustryProductServiceV2.0}RequestAddress" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InquiryDetail", propOrder = {
    "industryCode",
    "location"
})
public class InquiryDetail {

    @XmlElement(name = "IndustryCode")
    protected InquiryIndustryCodeType industryCode;
    @XmlElement(name = "Location")
    protected RequestAddress location;

    /**
     * Gets the value of the industryCode property.
     * 
     * @return
     *     possible object is
     *     {@link InquiryIndustryCodeType }
     *     
     */
    public InquiryIndustryCodeType getIndustryCode() {
        return industryCode;
    }

    /**
     * Sets the value of the industryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link InquiryIndustryCodeType }
     *     
     */
    public void setIndustryCode(InquiryIndustryCodeType value) {
        this.industryCode = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link RequestAddress }
     *     
     */
    public RequestAddress getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestAddress }
     *     
     */
    public void setLocation(RequestAddress value) {
        this.location = value;
    }

}
