//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 01:48:05 PM EET 
//


package com.dnb.services.industry;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.dnb.services.industryproductservicev2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _OrderProductResponse_QNAME = new QName("http://services.dnb.com/IndustryProductServiceV2.0", "OrderProductResponse");
    private final static QName _RetrieveProductRequest_QNAME = new QName("http://services.dnb.com/IndustryProductServiceV2.0", "RetrieveProductRequest");
    private final static QName _OrderProductRequest_QNAME = new QName("http://services.dnb.com/IndustryProductServiceV2.0", "OrderProductRequest");
    private final static QName _RetrieveProductResponse_QNAME = new QName("http://services.dnb.com/IndustryProductServiceV2.0", "RetrieveProductResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.dnb.services.industryproductservicev2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OrderProductResponse }
     * 
     */
    public OrderProductResponse createOrderProductResponse() {
        return new OrderProductResponse();
    }

    /**
     * Create an instance of {@link RetrieveProductRequest }
     * 
     */
    public RetrieveProductRequest createRetrieveProductRequest() {
        return new RetrieveProductRequest();
    }

    /**
     * Create an instance of {@link OrderProductRequest }
     * 
     */
    public OrderProductRequest createOrderProductRequest() {
        return new OrderProductRequest();
    }

    /**
     * Create an instance of {@link RetrieveProductResponse }
     * 
     */
    public RetrieveProductResponse createRetrieveProductResponse() {
        return new RetrieveProductResponse();
    }

    /**
     * Create an instance of {@link ProfileLocation }
     * 
     */
    public ProfileLocation createProfileLocation() {
        return new ProfileLocation();
    }

    /**
     * Create an instance of {@link SubChapterContentDetail }
     * 
     */
    public SubChapterContentDetail createSubChapterContentDetail() {
        return new SubChapterContentDetail();
    }

    /**
     * Create an instance of {@link RetrieveProductRequestDetail }
     * 
     */
    public RetrieveProductRequestDetail createRetrieveProductRequestDetail() {
        return new RetrieveProductRequestDetail();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link ResponseArchiveDetail }
     * 
     */
    public ResponseArchiveDetail createResponseArchiveDetail() {
        return new ResponseArchiveDetail();
    }

    /**
     * Create an instance of {@link OrderProductResponseDetail }
     * 
     */
    public OrderProductResponseDetail createOrderProductResponseDetail() {
        return new OrderProductResponseDetail();
    }

    /**
     * Create an instance of {@link OrderProductRequestDetail }
     * 
     */
    public OrderProductRequestDetail createOrderProductRequestDetail() {
        return new OrderProductRequestDetail();
    }

    /**
     * Create an instance of {@link SimpleAddress }
     * 
     */
    public SimpleAddress createSimpleAddress() {
        return new SimpleAddress();
    }

    /**
     * Create an instance of {@link TransactionResult }
     * 
     */
    public TransactionResult createTransactionResult() {
        return new TransactionResult();
    }

    /**
     * Create an instance of {@link IndustryProfile }
     * 
     */
    public IndustryProfile createIndustryProfile() {
        return new IndustryProfile();
    }

    /**
     * Create an instance of {@link ResponseTransactionDetail }
     * 
     */
    public ResponseTransactionDetail createResponseTransactionDetail() {
        return new ResponseTransactionDetail();
    }

    /**
     * Create an instance of {@link ChapterContentDetail }
     * 
     */
    public ChapterContentDetail createChapterContentDetail() {
        return new ChapterContentDetail();
    }

    /**
     * Create an instance of {@link LocationProfile }
     * 
     */
    public LocationProfile createLocationProfile() {
        return new LocationProfile();
    }

    /**
     * Create an instance of {@link LocationProfileDetail }
     * 
     */
    public LocationProfileDetail createLocationProfileDetail() {
        return new LocationProfileDetail();
    }

    /**
     * Create an instance of {@link ArchiveDetail }
     * 
     */
    public ArchiveDetail createArchiveDetail() {
        return new ArchiveDetail();
    }

    /**
     * Create an instance of {@link RetrieveProductResponseDetail }
     * 
     */
    public RetrieveProductResponseDetail createRetrieveProductResponseDetail() {
        return new RetrieveProductResponseDetail();
    }

    /**
     * Create an instance of {@link PrimaryIndustryCodeType }
     * 
     */
    public PrimaryIndustryCodeType createPrimaryIndustryCodeType() {
        return new PrimaryIndustryCodeType();
    }

    /**
     * Create an instance of {@link ResponseIndustryCodeType }
     * 
     */
    public ResponseIndustryCodeType createResponseIndustryCodeType() {
        return new ResponseIndustryCodeType();
    }

    /**
     * Create an instance of {@link InquiryIndustryCodeType }
     * 
     */
    public InquiryIndustryCodeType createInquiryIndustryCodeType() {
        return new InquiryIndustryCodeType();
    }

    /**
     * Create an instance of {@link RequestAddress }
     * 
     */
    public RequestAddress createRequestAddress() {
        return new RequestAddress();
    }

    /**
     * Create an instance of {@link Message }
     * 
     */
    public Message createMessage() {
        return new Message();
    }

    /**
     * Create an instance of {@link InquiryReferenceDetail }
     * 
     */
    public InquiryReferenceDetail createInquiryReferenceDetail() {
        return new InquiryReferenceDetail();
    }

    /**
     * Create an instance of {@link RequestTransactionDetail }
     * 
     */
    public RequestTransactionDetail createRequestTransactionDetail() {
        return new RequestTransactionDetail();
    }

    /**
     * Create an instance of {@link RetrieveProductArchiveDetail }
     * 
     */
    public RetrieveProductArchiveDetail createRetrieveProductArchiveDetail() {
        return new RetrieveProductArchiveDetail();
    }

    /**
     * Create an instance of {@link IndustryChapterDetail }
     * 
     */
    public IndustryChapterDetail createIndustryChapterDetail() {
        return new IndustryChapterDetail();
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link ResultMessage }
     * 
     */
    public ResultMessage createResultMessage() {
        return new ResultMessage();
    }

    /**
     * Create an instance of {@link IndustryCodeDescriptionType }
     * 
     */
    public IndustryCodeDescriptionType createIndustryCodeDescriptionType() {
        return new IndustryCodeDescriptionType();
    }

    /**
     * Create an instance of {@link ProductSpecification }
     * 
     */
    public ProductSpecification createProductSpecification() {
        return new ProductSpecification();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link ProfileSubChapterDetail }
     * 
     */
    public ProfileSubChapterDetail createProfileSubChapterDetail() {
        return new ProfileSubChapterDetail();
    }

    /**
     * Create an instance of {@link DNBDecodedStringType }
     * 
     */
    public DNBDecodedStringType createDNBDecodedStringType() {
        return new DNBDecodedStringType();
    }

    /**
     * Create an instance of {@link InquiryDetail }
     * 
     */
    public InquiryDetail createInquiryDetail() {
        return new InquiryDetail();
    }

    /**
     * Create an instance of {@link IndustryProfileDetail }
     * 
     */
    public IndustryProfileDetail createIndustryProfileDetail() {
        return new IndustryProfileDetail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderProductResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.dnb.com/IndustryProductServiceV2.0", name = "OrderProductResponse")
    public JAXBElement<OrderProductResponse> createOrderProductResponse(OrderProductResponse value) {
        return new JAXBElement<OrderProductResponse>(_OrderProductResponse_QNAME, OrderProductResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrieveProductRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.dnb.com/IndustryProductServiceV2.0", name = "RetrieveProductRequest")
    public JAXBElement<RetrieveProductRequest> createRetrieveProductRequest(RetrieveProductRequest value) {
        return new JAXBElement<RetrieveProductRequest>(_RetrieveProductRequest_QNAME, RetrieveProductRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrderProductRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.dnb.com/IndustryProductServiceV2.0", name = "OrderProductRequest")
    public JAXBElement<OrderProductRequest> createOrderProductRequest(OrderProductRequest value) {
        return new JAXBElement<OrderProductRequest>(_OrderProductRequest_QNAME, OrderProductRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrieveProductResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.dnb.com/IndustryProductServiceV2.0", name = "RetrieveProductResponse")
    public JAXBElement<RetrieveProductResponse> createRetrieveProductResponse(RetrieveProductResponse value) {
        return new JAXBElement<RetrieveProductResponse>(_RetrieveProductResponse_QNAME, RetrieveProductResponse.class, null, value);
    }

}
