//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 01:48:05 PM EET 
//


package com.dnb.services.industry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * Records data relating to requests for a product or products. This may include such details as the type of product required, the subject about which the product should be produced, the content of the product.
 *          
 * 
 * <p>Java class for OrderProductRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OrderProductRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://services.dnb.com/IndustryProductServiceV2.0}Request">
 *       &lt;sequence>
 *         &lt;element name="OrderProductRequestDetail" type="{http://services.dnb.com/IndustryProductServiceV2.0}OrderProductRequestDetail"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OrderProductRequest", propOrder = {
    "orderProductRequestDetail"
})
public class OrderProductRequest
    extends Request
{

    @XmlElement(name = "OrderProductRequestDetail", required = true)
    protected OrderProductRequestDetail orderProductRequestDetail;

    /**
     * Gets the value of the orderProductRequestDetail property.
     * 
     * @return
     *     possible object is
     *     {@link OrderProductRequestDetail }
     *     
     */
    public OrderProductRequestDetail getOrderProductRequestDetail() {
        return orderProductRequestDetail;
    }

    /**
     * Sets the value of the orderProductRequestDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderProductRequestDetail }
     *     
     */
    public void setOrderProductRequestDetail(OrderProductRequestDetail value) {
        this.orderProductRequestDetail = value;
    }

}
