//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.03.22 at 01:48:05 PM EET 
//


package com.dnb.services.industry;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Product complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Product">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DNBProductID" type="{http://services.dnb.com/IndustryProductServiceV2.0}ProductCode"/>
 *         &lt;element name="LanguageCode" type="{http://services.dnb.com/IndustryProductServiceV2.0}DNBCodeValueType" minOccurs="0"/>
 *         &lt;element name="IndustryProfile" type="{http://services.dnb.com/IndustryProductServiceV2.0}IndustryProfile" minOccurs="0"/>
 *         &lt;element name="LocationProfile" type="{http://services.dnb.com/IndustryProductServiceV2.0}LocationProfile" minOccurs="0"/>
 *         &lt;element name="ArchiveDetail" type="{http://services.dnb.com/IndustryProductServiceV2.0}ResponseArchiveDetail" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Product", propOrder = {
    "dnbProductID",
    "languageCode",
    "industryProfile",
    "locationProfile",
    "archiveDetail"
})
public class Product {

    @XmlElement(name = "DNBProductID", required = true)
    protected String dnbProductID;
    @XmlElement(name = "LanguageCode")
    protected BigInteger languageCode;
    @XmlElement(name = "IndustryProfile")
    protected IndustryProfile industryProfile;
    @XmlElement(name = "LocationProfile")
    protected LocationProfile locationProfile;
    @XmlElement(name = "ArchiveDetail")
    protected ResponseArchiveDetail archiveDetail;

    /**
     * Gets the value of the dnbProductID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDNBProductID() {
        return dnbProductID;
    }

    /**
     * Sets the value of the dnbProductID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDNBProductID(String value) {
        this.dnbProductID = value;
    }

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLanguageCode(BigInteger value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the industryProfile property.
     * 
     * @return
     *     possible object is
     *     {@link IndustryProfile }
     *     
     */
    public IndustryProfile getIndustryProfile() {
        return industryProfile;
    }

    /**
     * Sets the value of the industryProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndustryProfile }
     *     
     */
    public void setIndustryProfile(IndustryProfile value) {
        this.industryProfile = value;
    }

    /**
     * Gets the value of the locationProfile property.
     * 
     * @return
     *     possible object is
     *     {@link LocationProfile }
     *     
     */
    public LocationProfile getLocationProfile() {
        return locationProfile;
    }

    /**
     * Sets the value of the locationProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocationProfile }
     *     
     */
    public void setLocationProfile(LocationProfile value) {
        this.locationProfile = value;
    }

    /**
     * Gets the value of the archiveDetail property.
     * 
     * @return
     *     possible object is
     *     {@link ResponseArchiveDetail }
     *     
     */
    public ResponseArchiveDetail getArchiveDetail() {
        return archiveDetail;
    }

    /**
     * Sets the value of the archiveDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResponseArchiveDetail }
     *     
     */
    public void setArchiveDetail(ResponseArchiveDetail value) {
        this.archiveDetail = value;
    }

}
